- name: Deploys VM based on cloud image
  hosts: localhost
  gather_facts: true
  become: true
  vars:
    pool_dir: "/var/lib/libvirt/images"
    vm: arch
    vcpus: 2
    ram_mb: 2048
    cleanup: no
    net: default
    ssh_pub_key: "/home/dhip/.ssh/magnus.pub"

  tasks:
    - name: KVM Provision role
      include_role:
        name: kvm_provision
      vars:
        libvirt_pool_dir: "{{ pool_dir }}"
        vm_name: "{{ vm }}"
        vm_vcpus: "{{ vcpus }}"
        vm_ram_mb: "{{ ram_mb }}"
        vm_net: "{{ net }}"
        cleanup_tmp: "{{ cleanup }}"
        ssh_key: "{{ ssh_pub_key }}"

- name: Test on new host
  hosts: nodes
  tasks:
    - name: Test
      command: ip address
